### ISSUE TITLE
Multiple errors with clean install from requirements 

### ISSUE THREAD

**Issue by totial** [Riathoir/PASSGAN-IWGAN-Tensorflow-2#15]
Hey Rachel, the work you did here is amazing and I am trying to get the code working but Im getting multiple errors. Do you know if the code is working out of the box? Dont know where to start and if you have time to help me out. To be quick I tried using a conda environment with all the requirements installed (from requirements.txt) and another environment with an upgraded version of the libraries. No one worked after trying multiple versions (on libraries which failed) and tweaking the code avoiding warnings. Any recommendation? I dropped TF for pytorch a while ago and Im a bit rusty to say the least :P. Hope u have a nice day and wish u are able to reply :) 

Alex

**Comment by Riathoir** [comment]
Hi Alex, 
In terms of this code repository it is nearing 2 years old and should be considered a relic. It was extremely experimental at the time and showed unprecedented potential - to this day I'm still a little shocked at how good the result was as when the model gets traction it becomes quite the monster. 

You'll find my final dissertation setup notes below, and I will add a few warnings from memory. 

- Versions matter, the latest and greatest is not always backwards compatible. 
- use venv, conda is bad
- fixing issues is half the fun

Rachel

----------------------------
Installation for demonstration:
The appropriate environment for Tensorflow2.1rc0-GPU is difficult to setup and it is recommended where possible to initialize it through a docker environment. 
The development however was not conducted through docker and the instructions are as follows: 
Have an appropriate Nvidia GPU, used: GTX 980 Ti
Install Ubuntu 19.10+ Disco Dingo
Locate the text document in project root named TENSORFLOW SETUP


Follow the instructions to successfully install the CUDA binaries. 
Install Pycharm IDEA 
Open project using Pycharm IDEA at project root
Install the following project environment packages (if not automatically prompted)

Open the project environment terminal
Paste the command: python GAN.py -dataset rock_you -batch_size 64 -layer_dim 128 && tensorboard --log_dir logs/gradient_tape

The project will begin training on the rockyou dataset and tensorboard will start displaying the supervised component. Flags are detailed below:

**Comment by Riathoir** [comment]
This may be of interest 

[Final_Dissertation.docx](https://github.com/Riathoir/PASSGAN-IWGAN-Tensorflow-2/files/7954916/Final_Dissertation.docx)
